- name: Build Docker image
  run: docker build -t loc-mns-front .

- name: Deploy frontend
  run: |
    docker stop loc-mns-front || true
    docker rm loc-mns-front || true

    docker run -d \
      --name loc-mns-front \
      -p 80:80 \
      --restart unless-stopped \
      loc-mns-front
