name: Deploy Frontend

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t loc-mns-front .

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: draifis
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push docker image
        run: docker push draifis/loc-mns-front:latest
